### ISSUE TITLE
[BUG] I get accused of yelling at the student for using the acronym ASCII

### ISSUE THREAD

**Issue by alexschrod** [yyyc514/exercism_plus#10]
**Describe the bug**
Using "ASCII" anywhere in the regular text triggers "Don't YELL at your students, try bold or italics instead." 

**To Reproduce**
Type "ASCII" in a mentor comment box.

**Expected behavior**
To not see "Don't YELL at your students, try bold or italics instead." with legitimate acronyms. I notice it's not happening with other acronyms like HTML and HTTP, so there's clearly some list of acceptable acronyms somewhere.

**Comment by yyyc514** [comment]
HAHAHA, looks like this rule might need to be rethought.

**Comment by yyyc514** [comment]
If we change the pattern from `XXXXX+` to `XXX+ XXX+` are we going to run afoul of any two word common acronyms?

**Comment by kotp** [comment]
Or, since humans are smarter than computers, perhaps we can capture the thing that triggered the pattern, and determine if we accept the judgement or ignore it?

For instance, if I really do mean to address the student as "you" and they asked me to in some way, but I get a report of it... and then accidentally do so again, as the topic has changed, I would want to see that it triggered a second time, and where.

**Comment by yyyc514** [comment]
https://github.com/yyyc514/exercism_plus/commit/2b5f9d6fdde64b2919b1f705a49aa5372c143b9b

This is in master, will be in 0.7 release.  ASCII and POSIX are added as exceptions.
